version: "3"
services:
  dev:
    build:
      dockerfile: docker/Dockerfile
      context: .
      target: dev
    image: ${COTOWALI_IMAGE_PREFIX}cotowali-dev:${COTOWALI_IMAGE_TAG:-latest}
    environment:
      - COTOWALI_ROOT="${COTOWALI_ROOT:-/usr/local/cotowali}"
    volumes:
      - .:${COTOWALI_ROOT:-/usr/local/cotowali}
  dev-emscripten:
    build:
      dockerfile: docker/Dockerfile
      context: .
      target: dev-emscripten
    image: ${COTOWALI_IMAGE_PREFIX}cotowali-dev:emscripten-${COTOWALI_IMAGE_TAG:-latest}
    environment:
      - COTOWALI_ROOT="${COTOWALI_ROOT:-/usr/local/cotowali}"
    volumes:
      - .:${COTOWALI_ROOT:-/usr/local/cotowali}
