name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup V
        run: |
          git clone https://github.com/vlang/v /tmp/v && cd /tmp/v
          make && sudo ./v symlink
      - run: v fmt -verify .
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup V
        run: |
          git clone https://github.com/vlang/v /tmp/v && cd /tmp/v
          make && sudo ./v symlink
      - run: v test .
