name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: zakuro9715/setup-z@main
      - uses: actions/checkout@v2
      - run: z ci setup-v
      - run: z ci format
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cc: [clang, gcc]
    env:
      VFLAGS: "-cc ${{ matrix.cc }}"
    steps:
      - uses: zakuro9715/setup-z@main
      - uses: actions/checkout@v2
      - run: z ci setup-v
      - run: z ci test
  sanitize:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fsanitize: [memory, address, undefined]
    env:
      ASAN_OPTIONS: "detect_leaks=0"
      VFLAGS: "-cc clang -cflags '-fsanitize=${{ matrix.fsanitize }}'"
    steps:
      - uses: zakuro9715/setup-z@main
      - uses: actions/checkout@v2
      - run: z ci setup-v
      - run: z ci test
  run-on-all-conditions:
    runs-on: ubuntu-latest
    steps:
      - uses: zakuro9715/setup-z@main
      - uses: actions/checkout@v2
      - run: z ci setup-v
      - run: z ci run-on-all-conditions
  slack-notify:
    if: failure()
    needs: [format, test, sanitize, run-on-all-conditions]
    runs-on: ubuntu-latest
    steps:
      - uses: Gamesight/slack-workflow-status@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          channel: ${{ secrets.SLACK_WEBHOOK_CHANNELL }}
          name: 'GitHub Actions'
          icon_url: 'https://raw.githubusercontent/cotowari/logo/main/cotowari.png'
