name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: { repository: vlang/v }
      - run: make
      - uses: actions/checkout@v2
        with: { path: vash }
      - run: ./v fmt -verify vash
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: { repository: vlang/v }
      - run: make
      - uses: actions/checkout@v2
        with: { path: vash }
      - run: ./v test vash
