name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: { repository: vlang/v, path: ../v }
      - run: cd ../v && make && sudo ./v symlink
      - uses: actions/checkout@v2
      - run: v fmt -verify vash
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: { repository: vlang/v, path: ../v }
      - run: cd ../v && make && sudo ./v symlink
      - uses: actions/checkout@v2
      - run: v test
      - run: v run cmd/vash examples/hello.vash
