name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: zakuro9715/setup-z@main
      - uses: actions/checkout@v2
      - run: z ci setup-v
      - run: z ci format
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cc: [clang, gcc]
        test_arg: ['', 'prod']
    env:
      VFLAGS: "-cc ${{ matrix.cc }}"
    steps:
      - uses: zakuro9715/setup-z@main
      - uses: actions/checkout@v2
      - run: z ci setup-v
      - run: z ci test ${{ matrix.test_arg }}
  test-alpine:
    runs-on: ubuntu-latest
    env:
      VFLAGS: "-cc clang"
    steps:
      - uses: zakuro9715/setup-z@main
      - uses: actions/checkout@v2
      - run: z ci setup-v
      - run: z test compile
      - run: docker run -v $(pwd)/tests:/app/tests -w /app alpine ./tests/run.sh
  test-macos:
    runs-on: macos-latest
    env:
      VFLAGS: "-cc clang"
    steps:
      - uses: zakuro9715/setup-z@main
      - uses: actions/checkout@v2
      # https://github.com/vlang/v/blob/a84a6d1fb1b2b4025db88a883a4682c978212562/.github/workflows/ci.yml#L272-L273
      - run: |
          brew install openssl
          export LIBRARY_PATH="$LIBRARY_PATH:/usr/local/opt/openssl/lib/"
      - run: z ci setup-v
      - run: z ci test
# shellcheck:
#   runs-on: ubuntu-latest
#   strategy:
#     matrix:
#       cc: [clang, gcc]
#   env:
#     VFLAGS: "-cc ${{ matrix.cc }}"
#   steps:
#     - uses: zakuro9715/setup-z@main
#     - uses: actions/checkout@v2
#     - run: z ci setup-v
#     - run: z ci test shellcheck
  sanitize:
   runs-on: ubuntu-latest
   strategy:
     matrix:
       fsanitize:
         - address
   env:
     ASAN_OPTIONS: "detect_leaks=0"
     VFLAGS: "-cc clang -cflags '-fsanitize=${{ matrix.fsanitize }}'"
   steps:
     - uses: zakuro9715/setup-z@main
     - uses: actions/checkout@v2
     - run: z ci setup-v
     - run: z ci test
  run-on-all-conditions:
    runs-on: ubuntu-latest
    steps:
      - uses: zakuro9715/setup-z@main
      - uses: actions/checkout@v2
      - run: z ci setup-v
#  # double free error
#  # https://github.com/cotowali/cotowali/runs/4276302273
#      - run: z ci run-on-all-conditions
  slack-notify:
    if: failure()
    needs: [format, test, test-alpine, test-macos, sanitize, run-on-all-conditions]
    runs-on: ubuntu-latest
    steps:
      - uses: Gamesight/slack-workflow-status@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          channel: ${{ secrets.SLACK_WEBHOOK_CHANNELL }}
          name: 'GitHub Actions'
          icon_url: 'https://raw.githubusercontent/cotowari/logo/main/cotowari.png'
