name: Release

on:
  push:
    tags:
      - '*'

env:
  COTOWALI_HASH: "${{ github.sha }}"
  VFLAGS: "-cc clang"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: zakuro9715/setup-z@main
      - uses: actions/checkout@v2
      - run: z ci setup-v
      - run: z build
      - run: ./bin/lic run scripts/pack.li
      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux
          path: dist/*
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: zakuro9715/setup-z@main
      - uses: actions/checkout@v2
      - run: z ci setup-v
      - run: z build
      - run: ./bin/lic run scripts/pack.li
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: macos
          path: dist/*
  release:
    needs: [build-linux, build-macos]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            linux/*.tar.gz
            macos/*.tar.gz
